#!/usr/bin/env python3
"""De-risk study ①: open-vocab binding behavior on WM-GENERATED rollouts.

The field has zero published data on detect/segment/track reliability under
GENERATIVE failure modes (drift, morphing, vanishing) — every robustness suite
uses photometric corruptions on real video. This study measures it on real
world-model rollouts (Cosmos-3 FD pipette task, 54 rollouts across 4 policies
incl. random, all generated by the same WM).

What it measures (no per-frame human boxes exist, so these are the honest
label-free observables — stated plainly in the report):
  M1 bind rate + quality per role per policy
  M2 REAL-vs-GENERATED detection gap: rollouts start from a REAL observation,
     so frame-0 detection is a within-video real-frame baseline; late-window
     detection measures the generated/drifted regime. The delta is the
     generative-degradation signal nobody has published.
  M3 visibility/persistence statistics over time per policy (does tracker
     confidence collapse correlate with policy quality / drift?)
  M4 overlay videos for qualitative audit (every claim inspectable).

Usage:
  uv run --extra ground python studies/binding/run_study.py \
      --per-policy 2 --stride 8 --out studies/binding/out
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np

REPO = "ZoreAnuj/cosmos3-rh20t-pipette-fd-lora"
POLICIES = ["act_010000", "act_050000", "smolvla", "random"]


def fetch_rollouts(per_policy: int, cache_dir: str) -> list[tuple[str, str]]:
    """Download mp4 rollouts from the HF artifact repo -> [(policy, path)]."""
    from huggingface_hub import hf_hub_download, list_repo_files

    token = os.environ.get("HF_TOKEN")
    files = list_repo_files(REPO, token=token)
    out: list[tuple[str, str]] = []
    for pol in POLICIES:
        vids = sorted(
            f for f in files if f.startswith(f"stage3/rollouts_2min/{pol}/") and f.endswith(".mp4")
        )[:per_policy]
        for v in vids:
            path = hf_hub_download(REPO, v, token=token, cache_dir=cache_dir)
            out.append((pol, path))
    return out


def window_stats(vis: np.ndarray, frac: tuple[float, float]) -> dict:
    lo, hi = int(len(vis) * frac[0]), max(int(len(vis) * frac[1]), int(len(vis) * frac[0]) + 1)
    w = vis[lo:hi]
    return {
        "mean_vis": round(float(w.mean()), 4),
        "frac_detected": round(float((w > 0).mean()), 4),
    }


def overlay_video(frames: np.ndarray, tracks: dict[str, np.ndarray], path: str) -> None:
    import imageio.v3 as iio

    colors = {"carried_object": (255, 0, 0), "receptacle": (0, 255, 0), "gripper": (0, 0, 255)}
    out = frames.copy()
    for role, tr in tracks.items():
        c = colors.get(role, (255, 255, 0))
        for t in range(len(out)):
            if t < len(tr) and np.isfinite(tr[t]).all():
                x, y = int(tr[t, 0]), int(tr[t, 1])
                y0, y1 = max(0, y - 2), min(out.shape[1], y + 3)
                x0, x1 = max(0, x - 2), min(out.shape[2], x + 3)
                out[t, y0:y1, x0:x1] = c
    iio.imwrite(path, out, fps=10, codec="libx264")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-policy", type=int, default=2)
    ap.add_argument("--stride", type=int, default=8)
    ap.add_argument("--det-threshold", type=float, default=0.2)
    ap.add_argument("--tiles", type=int, default=1)
    ap.add_argument("--out", default="studies/binding/out")
    ap.add_argument("--cache", default=os.path.expanduser("~/.cache/woracle/study"))
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    from woracle.contracts import load_spec
    from woracle.grounders.openvocab import OpenVocabGrounder
    from woracle.io import load_frames
    from woracle.io.video import rollout_from_video

    spec = load_spec(
        os.path.join(
            os.path.dirname(__file__), "..", "..", "specs", "rh20t-pipette-insert", "spec.yaml"
        )
    )
    grounder = OpenVocabGrounder(
        stride=args.stride, det_threshold=args.det_threshold, tiles=args.tiles
    )

    print(f"fetching {args.per_policy}/policy rollouts from {REPO} ...", flush=True)
    items = fetch_rollouts(args.per_policy, args.cache)
    if not items:
        print("no rollouts found — check HF_TOKEN / repo layout", file=sys.stderr)
        return 2

    rows = []
    for pol, path in items:
        rid = f"{pol}_{os.path.splitext(os.path.basename(path))[0]}"
        print(f"[{rid}] grounding ...", flush=True)
        ref = rollout_from_video(path, rollout_id=rid, policy=pol, source="wm:cosmos3")
        gdir = os.path.join(args.out, "grounded", rid)
        os.makedirs(gdir, exist_ok=True)
        grounded = grounder.ground(ref, spec, gdir)

        frames = load_frames(ref)
        tracks: dict[str, np.ndarray] = {}
        row: dict = {"rollout": rid, "policy": pol, "n_frames": int(frames.shape[0]), "roles": {}}
        for b in grounded.bindings:
            entry: dict = {"bound": b.bound, "quality": round(b.quality, 4), "reason": b.reason}
            if b.bound and b.visibility is not None:
                with np.load(b.visibility.resolve(gdir)) as z:
                    vis = z["vis"]
                entry["early_real_window"] = window_stats(vis, (0.0, 0.05))  # frame-0 anchor era
                entry["mid_window"] = window_stats(vis, (0.30, 0.50))
                entry["late_window"] = window_stats(vis, (0.80, 1.00))
                entry["real_to_late_drop"] = round(
                    entry["early_real_window"]["mean_vis"] - entry["late_window"]["mean_vis"], 4
                )
            if b.bound and b.tracks is not None:
                with np.load(b.tracks.resolve(gdir)) as z:
                    tr = z["track"]
                tracks[b.role] = tr
                d = np.linalg.norm(np.diff(tr[np.isfinite(tr[:, 0])], axis=0), axis=1)
                entry["track_jitter_p90"] = (
                    round(float(np.percentile(d, 90)), 2) if len(d) else None
                )
            row["roles"][b.role] = entry
        rows.append(row)
        overlay_video(frames, tracks, os.path.join(args.out, f"{rid}_overlay.mp4"))
        print(
            f"[{rid}] done: "
            + ", ".join(
                f"{r}={'B' if e['bound'] else 'U'}({e['quality']:.2f})"
                for r, e in row["roles"].items()
            ),
            flush=True,
        )

    # ---- aggregate ----
    agg: dict = {
        "per_policy": {},
        "notes": [
            "No per-frame human boxes exist for these rollouts; metrics are label-free "
            "observables (bind rate, real-vs-generated detection gap, persistence).",
            "Frame-0 window is REAL (WM rollouts start from a real observation); late "
            "window is fully generated — the drop is the generative-degradation signal.",
        ],
    }
    for pol in POLICIES:
        prows = [r for r in rows if r["policy"] == pol]
        if not prows:
            continue
        roles = {}
        for role in [x.name for x in spec.roles]:
            es = [r["roles"][role] for r in prows if role in r["roles"]]
            bound = [e for e in es if e["bound"]]
            roles[role] = {
                "bind_rate": round(len(bound) / len(es), 3) if es else None,
                "mean_quality": round(float(np.mean([e["quality"] for e in bound])), 3)
                if bound
                else None,
                "mean_real_to_late_drop": round(
                    float(
                        np.mean([e["real_to_late_drop"] for e in bound if "real_to_late_drop" in e])
                    ),
                    3,
                )
                if any("real_to_late_drop" in e for e in bound)
                else None,
            }
        agg["per_policy"][pol] = roles

    with open(os.path.join(args.out, "study.json"), "w") as f:
        json.dump(
            {
                "rows": rows,
                "aggregate": agg,
                "config": {
                    "stride": args.stride,
                    "det_threshold": args.det_threshold,
                    "per_policy": args.per_policy,
                    "grounder": grounder.params,
                },
            },
            f,
            indent=2,
        )
    print(json.dumps(agg, indent=2))
    print(f"\nfull results -> {args.out}/study.json ; overlays -> {args.out}/*_overlay.mp4")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
